## Training the model

In [1]:
from ultralytics import YOLO

# Load a model

model = YOLO("yolo11l.pt")  # load a pretrained model 

# Train the model
results = model.train(data="data.yaml", epochs=100, imgsz=640)


New https://pypi.org/project/ultralytics/8.3.38 available  Update with 'pip install -U ultralytics'
Ultralytics 8.3.36  Python-3.12.4 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4060, 8187MiB)
engine\trainer: task=detect, mode=train, model=yolo11l.pt, data=data.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=Fals

train: Scanning C:\VSCode\CrossyRoad\Crossy-Road-Course-Project\YOLO11_dataset\Crossy Road RL Agent\labels\train.cache... 75 images, 0 backgrounds, 0 corrupt: 100%|██████████| 75/75 [00:00<?, ?it/s]


albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, num_output_channels=3, method='weighted_average'), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))


val: Scanning C:\VSCode\CrossyRoad\Crossy-Road-Course-Project\YOLO11_dataset\Crossy Road RL Agent\labels\val.cache... 15 images, 0 backgrounds, 0 corrupt: 100%|██████████| 15/15 [00:00<?, ?it/s]


Plotting labels to runs\detect\train2\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.001111, momentum=0.9) with parameter groups 167 weight(decay=0.0), 174 weight(decay=0.0005), 173 bias(decay=0.0)
TensorBoard: model graph visualization added 
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs\detect\train2
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      1/100      11.1G      1.502      4.178      1.447        288        640: 100%|██████████| 5/5 [00:38<00:00,  7.78s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.56s/it]

                   all         15        240     0.0066      0.107    0.00869    0.00675



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      2/100      11.2G      1.316      3.577      1.344        295        640: 100%|██████████| 5/5 [00:36<00:00,  7.36s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.15s/it]

                   all         15        240      0.572      0.541      0.541      0.393



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      3/100      11.1G     0.8671      0.945      1.018        455        640: 100%|██████████| 5/5 [00:40<00:00,  8.18s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.63s/it]

                   all         15        240       0.64      0.803      0.778      0.541



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      4/100      11.1G     0.8265     0.7332      1.001        259        640: 100%|██████████| 5/5 [00:41<00:00,  8.23s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.42s/it]

                   all         15        240      0.766      0.807      0.901      0.658



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      5/100      11.1G     0.8132     0.6193     0.9814        284        640: 100%|██████████| 5/5 [01:09<00:00, 13.95s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:04<00:00,  4.35s/it]

                   all         15        240      0.812      0.882      0.896      0.685



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      6/100        11G     0.8353     0.6239      0.992        292        640: 100%|██████████| 5/5 [01:08<00:00, 13.63s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.66s/it]

                   all         15        240      0.792      0.882      0.882      0.617



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      7/100      11.1G     0.7996     0.5751      1.001        253        640: 100%|██████████| 5/5 [01:21<00:00, 16.22s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.39s/it]

                   all         15        240      0.731      0.792      0.826      0.627



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      8/100        11G     0.8067     0.5459     0.9775        384        640: 100%|██████████| 5/5 [01:27<00:00, 17.44s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:04<00:00,  4.37s/it]

                   all         15        240      0.794       0.87      0.819      0.587



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      9/100      11.1G     0.8104     0.5673     0.9986        235        640: 100%|██████████| 5/5 [01:01<00:00, 12.36s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.45s/it]

                   all         15        240       0.85      0.866      0.862       0.61



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     10/100      11.1G     0.8152     0.5687      1.011        316        640: 100%|██████████| 5/5 [00:39<00:00,  7.93s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.10s/it]

                   all         15        240      0.618      0.706      0.677      0.491



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     11/100      11.1G     0.8142     0.5391      1.001        330        640: 100%|██████████| 5/5 [00:39<00:00,  7.84s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.06s/it]

                   all         15        240      0.862      0.824      0.856      0.621



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     12/100      11.1G     0.7993     0.5454     0.9984        251        640: 100%|██████████| 5/5 [01:06<00:00, 13.26s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.11s/it]

                   all         15        240      0.858      0.839      0.909      0.669



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     13/100      11.1G     0.8328     0.5404     0.9903        295        640: 100%|██████████| 5/5 [01:20<00:00, 16.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:03<00:00,  3.14s/it]

                   all         15        240       0.85      0.818      0.887      0.653



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     14/100      11.1G     0.8339     0.5133      1.012        307        640: 100%|██████████| 5/5 [01:24<00:00, 16.99s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.46s/it]

                   all         15        240      0.817      0.883      0.838      0.611



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     15/100      11.2G     0.8058     0.5235       1.02        323        640: 100%|██████████| 5/5 [01:27<00:00, 17.54s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:03<00:00,  3.58s/it]

                   all         15        240      0.789       0.86      0.835      0.606



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     16/100      11.1G     0.8137     0.5281      1.007        383        640: 100%|██████████| 5/5 [01:24<00:00, 16.95s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:03<00:00,  3.98s/it]

                   all         15        240       0.77      0.867      0.825      0.589



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     17/100      11.1G     0.7697     0.5218     0.9872        329        640: 100%|██████████| 5/5 [01:25<00:00, 17.06s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:03<00:00,  3.16s/it]

                   all         15        240      0.725      0.894      0.831      0.612



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     18/100      11.1G      0.792     0.5536     0.9935        346        640: 100%|██████████| 5/5 [01:07<00:00, 13.41s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.30s/it]

                   all         15        240      0.765      0.875      0.795      0.582



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     19/100      11.1G      0.836     0.5821      1.019        303        640: 100%|██████████| 5/5 [00:50<00:00, 10.18s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.57s/it]

                   all         15        240      0.749      0.878      0.844      0.607



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     20/100      11.1G     0.8152     0.5864      1.005        296        640: 100%|██████████| 5/5 [00:41<00:00,  8.35s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.65s/it]

                   all         15        240      0.783       0.85      0.863      0.607



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     21/100      11.1G     0.8182     0.5509      1.004        374        640: 100%|██████████| 5/5 [00:44<00:00,  8.99s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.04s/it]

                   all         15        240      0.618      0.852      0.748      0.549



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     22/100      11.2G     0.7902     0.5288     0.9957        307        640: 100%|██████████| 5/5 [00:47<00:00,  9.57s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.97s/it]

                   all         15        240      0.656      0.784      0.713      0.527



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     23/100      11.1G     0.8125      0.537          1        280        640: 100%|██████████| 5/5 [00:44<00:00,  8.85s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.77s/it]

                   all         15        240      0.766      0.852      0.845      0.621



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     24/100      11.1G     0.7834     0.5313      1.002        290        640: 100%|██████████| 5/5 [00:39<00:00,  7.87s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.79s/it]

                   all         15        240      0.848      0.878      0.883      0.653



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     25/100      11.1G     0.8184     0.5354      1.008        281        640: 100%|██████████| 5/5 [00:43<00:00,  8.65s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.97s/it]

                   all         15        240       0.82      0.885      0.904      0.675



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     26/100      11.1G     0.7712     0.5084      0.996        299        640: 100%|██████████| 5/5 [00:39<00:00,  7.97s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.03s/it]

                   all         15        240      0.803      0.936      0.905      0.661



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     27/100      11.1G     0.7806     0.4952     0.9772        347        640: 100%|██████████| 5/5 [00:41<00:00,  8.22s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.05s/it]

                   all         15        240      0.811      0.894      0.864      0.633



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     28/100      11.1G     0.7552     0.4954     0.9709        347        640: 100%|██████████| 5/5 [00:42<00:00,  8.48s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.94s/it]

                   all         15        240      0.751      0.901       0.82      0.605



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     29/100        11G     0.7529      0.478     0.9774        239        640: 100%|██████████| 5/5 [00:42<00:00,  8.46s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.97s/it]

                   all         15        240      0.773      0.867      0.864      0.642



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     30/100      11.1G     0.7491     0.4822     0.9899        334        640: 100%|██████████| 5/5 [00:40<00:00,  8.06s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.73s/it]

                   all         15        240      0.814      0.902      0.877      0.662



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     31/100      11.1G     0.7386     0.4704     0.9735        358        640: 100%|██████████| 5/5 [00:40<00:00,  8.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.71s/it]

                   all         15        240       0.87        0.9      0.925      0.726



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     32/100      11.1G     0.7416       0.46     0.9751        339        640: 100%|██████████| 5/5 [00:40<00:00,  8.09s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.75s/it]

                   all         15        240      0.864      0.893      0.914      0.718



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     33/100      11.1G     0.7429     0.4618     0.9597        419        640: 100%|██████████| 5/5 [00:43<00:00,  8.64s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.86s/it]

                   all         15        240      0.879      0.891      0.916      0.711



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     34/100      11.1G     0.7256     0.4522     0.9514        309        640: 100%|██████████| 5/5 [00:45<00:00,  9.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.97s/it]

                   all         15        240      0.871      0.914      0.915      0.724



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     35/100      11.1G     0.7215     0.4495     0.9602        289        640: 100%|██████████| 5/5 [00:50<00:00, 10.07s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.33s/it]

                   all         15        240      0.865       0.91      0.922       0.73



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     36/100      11.1G     0.7237     0.4396     0.9588        326        640: 100%|██████████| 5/5 [00:44<00:00,  8.85s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.21s/it]

                   all         15        240      0.854      0.938      0.932       0.74



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     37/100        11G     0.7007     0.4358     0.9541        290        640: 100%|██████████| 5/5 [00:45<00:00,  9.05s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.51s/it]

                   all         15        240      0.881       0.89      0.927      0.733



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     38/100      11.1G     0.6865     0.4233     0.9415        366        640: 100%|██████████| 5/5 [00:38<00:00,  7.61s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.12s/it]

                   all         15        240      0.913       0.86      0.927      0.732



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     39/100      11.1G     0.7049     0.4288     0.9487        313        640: 100%|██████████| 5/5 [00:39<00:00,  7.91s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.40s/it]

                   all         15        240      0.876      0.923      0.932       0.71



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     40/100      11.2G     0.7095     0.4265     0.9608        290        640: 100%|██████████| 5/5 [00:38<00:00,  7.77s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.04s/it]

                   all         15        240      0.837       0.95      0.917      0.721



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     41/100      11.1G      0.689     0.4377     0.9464        292        640: 100%|██████████| 5/5 [00:41<00:00,  8.35s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.81s/it]

                   all         15        240      0.909      0.905      0.925      0.728



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     42/100      11.1G      0.708     0.4398     0.9588        246        640: 100%|██████████| 5/5 [00:41<00:00,  8.27s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.84s/it]

                   all         15        240      0.907      0.956      0.941       0.75



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     43/100      11.1G     0.6816     0.4096     0.9409        369        640: 100%|██████████| 5/5 [00:39<00:00,  7.99s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.05s/it]

                   all         15        240       0.91      0.929      0.935      0.751



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     44/100      11.1G     0.6685     0.4137     0.9458        360        640: 100%|██████████| 5/5 [00:41<00:00,  8.35s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.92s/it]

                   all         15        240      0.906      0.899      0.918      0.706



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     45/100      11.1G     0.6814     0.4291      0.958        264        640: 100%|██████████| 5/5 [00:39<00:00,  7.98s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.54s/it]

                   all         15        240      0.908      0.895      0.917      0.727



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     46/100      11.1G     0.6644     0.4153     0.9437        328        640: 100%|██████████| 5/5 [00:38<00:00,  7.78s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.76s/it]

                   all         15        240      0.891       0.89      0.912      0.733



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     47/100      11.1G     0.6609     0.4051     0.9421        361        640: 100%|██████████| 5/5 [00:39<00:00,  7.99s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.56s/it]

                   all         15        240      0.903        0.9      0.926      0.735



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     48/100      11.1G     0.6548     0.4114     0.9321        338        640: 100%|██████████| 5/5 [00:37<00:00,  7.45s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.81s/it]

                   all         15        240      0.886      0.934      0.924      0.734



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     49/100        11G     0.6598     0.4063     0.9427        290        640: 100%|██████████| 5/5 [00:36<00:00,  7.34s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.06it/s]

                   all         15        240      0.895      0.958      0.923       0.73



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     50/100      11.1G     0.6627     0.4029     0.9601        218        640: 100%|██████████| 5/5 [00:41<00:00,  8.27s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.92s/it]

                   all         15        240      0.929      0.931      0.924      0.739



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     51/100      11.1G     0.6241     0.3885      0.924        353        640: 100%|██████████| 5/5 [00:40<00:00,  8.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.95s/it]

                   all         15        240      0.917      0.902      0.926      0.733



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     52/100      11.1G     0.6415     0.4013     0.9397        260        640: 100%|██████████| 5/5 [00:41<00:00,  8.36s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.12s/it]

                   all         15        240      0.872      0.952      0.932      0.735



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     53/100      11.1G     0.6303      0.376     0.9261        349        640: 100%|██████████| 5/5 [00:40<00:00,  8.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.71s/it]

                   all         15        240      0.904      0.906      0.948      0.753



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     54/100      11.1G     0.6378     0.3823     0.9292        297        640: 100%|██████████| 5/5 [00:38<00:00,  7.68s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.59s/it]

                   all         15        240      0.873      0.979      0.963      0.757



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     55/100      11.1G      0.629     0.3824      0.925        362        640: 100%|██████████| 5/5 [00:35<00:00,  7.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.02s/it]

                   all         15        240      0.894      0.987      0.965      0.761



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     56/100      11.1G      0.631     0.3895     0.9234        310        640: 100%|██████████| 5/5 [00:37<00:00,  7.42s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.61s/it]

                   all         15        240      0.885      0.984      0.957       0.76



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     57/100        11G     0.6266     0.3886     0.9355        394        640: 100%|██████████| 5/5 [00:37<00:00,  7.52s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.02it/s]

                   all         15        240      0.922      0.925      0.952      0.762



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     58/100      11.1G     0.6274     0.3807     0.9309        302        640: 100%|██████████| 5/5 [00:46<00:00,  9.40s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.01s/it]

                   all         15        240      0.893      0.961      0.957       0.76



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     59/100      11.1G     0.6294     0.3847     0.9206        350        640: 100%|██████████| 5/5 [00:47<00:00,  9.51s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.24s/it]

                   all         15        240      0.888       0.96      0.935      0.756



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     60/100      11.1G     0.6031     0.3619     0.9185        359        640: 100%|██████████| 5/5 [00:48<00:00,  9.75s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.18s/it]

                   all         15        240      0.882      0.946      0.934      0.755



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     61/100      11.1G     0.6008     0.3664     0.9151        379        640: 100%|██████████| 5/5 [00:48<00:00,  9.64s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.57s/it]

                   all         15        240      0.906      0.913      0.932      0.749



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     62/100      11.1G     0.6198     0.3712      0.926        413        640: 100%|██████████| 5/5 [00:41<00:00,  8.29s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.53s/it]

                   all         15        240      0.913      0.913      0.935      0.752



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     63/100      11.1G     0.6044     0.3599     0.9211        424        640: 100%|██████████| 5/5 [00:41<00:00,  8.37s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.10s/it]

                   all         15        240      0.925      0.909      0.942      0.761



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     64/100      11.1G     0.6037     0.3642     0.9166        221        640: 100%|██████████| 5/5 [00:40<00:00,  8.00s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.23s/it]

                   all         15        240      0.923      0.906      0.932      0.762



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     65/100      11.1G     0.5981     0.3682     0.9168        273        640: 100%|██████████| 5/5 [00:41<00:00,  8.34s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.90s/it]

                   all         15        240      0.926      0.913      0.938      0.766



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     66/100      11.1G     0.6057     0.3742     0.9246        362        640: 100%|██████████| 5/5 [00:37<00:00,  7.58s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]

                   all         15        240      0.901      0.943      0.952      0.768



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     67/100      11.1G     0.6111     0.3755     0.9306        282        640: 100%|██████████| 5/5 [00:39<00:00,  7.86s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.41s/it]

                   all         15        240      0.898      0.952      0.932      0.745



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     68/100      11.1G     0.6051     0.3654     0.9233        313        640: 100%|██████████| 5/5 [00:42<00:00,  8.45s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.48s/it]

                   all         15        240      0.876      0.964      0.933      0.751



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     69/100      11.1G     0.5809     0.3455      0.908        326        640: 100%|██████████| 5/5 [00:41<00:00,  8.24s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.18s/it]

                   all         15        240      0.899      0.929      0.927      0.756



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     70/100      11.1G     0.5789      0.348     0.9188        279        640: 100%|██████████| 5/5 [00:40<00:00,  8.03s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.38s/it]

                   all         15        240      0.892      0.937      0.931      0.744



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     71/100      11.1G     0.5852     0.3516     0.9035        337        640: 100%|██████████| 5/5 [00:42<00:00,  8.50s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.94s/it]

                   all         15        240        0.9      0.924      0.938      0.747



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     72/100      11.1G     0.5793     0.3492     0.8984        406        640: 100%|██████████| 5/5 [00:38<00:00,  7.77s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.15s/it]

                   all         15        240      0.887      0.959      0.933      0.755



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     73/100        11G     0.5775     0.3472     0.9042        308        640: 100%|██████████| 5/5 [00:38<00:00,  7.75s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.27s/it]

                   all         15        240      0.896      0.962      0.938      0.761



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     74/100      11.1G      0.576     0.3524     0.9124        204        640: 100%|██████████| 5/5 [00:40<00:00,  8.06s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.90s/it]

                   all         15        240      0.895      0.962       0.95      0.768



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     75/100      11.1G     0.5616     0.3398     0.8912        303        640: 100%|██████████| 5/5 [00:46<00:00,  9.26s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.24s/it]

                   all         15        240      0.898      0.957      0.957      0.779



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     76/100      11.1G     0.5748     0.3497     0.9017        339        640: 100%|██████████| 5/5 [00:48<00:00,  9.64s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.22s/it]

                   all         15        240      0.924      0.947      0.957      0.784



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     77/100      11.1G     0.5663     0.3398     0.9065        272        640: 100%|██████████| 5/5 [00:42<00:00,  8.48s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.27s/it]

                   all         15        240       0.93      0.934      0.955      0.785



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     78/100      11.1G     0.5589     0.3408     0.8978        315        640: 100%|██████████| 5/5 [00:41<00:00,  8.22s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.97s/it]

                   all         15        240      0.934      0.939      0.959      0.791



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     79/100      11.1G     0.5505     0.3342     0.8999        334        640: 100%|██████████| 5/5 [00:35<00:00,  7.01s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.87s/it]

                   all         15        240      0.899      0.966      0.955      0.782



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     80/100      11.1G     0.5353     0.3217     0.8904        332        640: 100%|██████████| 5/5 [00:36<00:00,  7.39s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.36s/it]

                   all         15        240      0.918      0.952       0.95      0.773



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     81/100      11.3G     0.5427     0.3223     0.9055        361        640: 100%|██████████| 5/5 [00:39<00:00,  7.85s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.24s/it]

                   all         15        240      0.923      0.953      0.959      0.782



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     82/100      11.1G     0.5564     0.3204     0.8943        340        640: 100%|██████████| 5/5 [00:36<00:00,  7.21s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.42s/it]

                   all         15        240      0.925      0.954      0.958      0.782



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     83/100      11.1G     0.5419     0.3262      0.903        281        640: 100%|██████████| 5/5 [00:35<00:00,  7.02s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.68s/it]

                   all         15        240      0.935      0.954      0.962       0.79



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     84/100      11.1G     0.5348     0.3249     0.8887        269        640: 100%|██████████| 5/5 [00:44<00:00,  9.00s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.02s/it]

                   all         15        240      0.913      0.965      0.953      0.787



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     85/100        11G     0.5297     0.3189     0.8878        304        640: 100%|██████████| 5/5 [00:52<00:00, 10.58s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.70s/it]

                   all         15        240      0.911      0.967      0.952      0.789



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     86/100      11.1G      0.527     0.3133     0.8935        240        640: 100%|██████████| 5/5 [00:52<00:00, 10.52s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.50s/it]

                   all         15        240      0.902      0.968      0.955      0.785



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     87/100      11.1G     0.5154     0.3088     0.8716        353        640: 100%|██████████| 5/5 [00:51<00:00, 10.21s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.48s/it]

                   all         15        240      0.902      0.939      0.946      0.781



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     88/100      11.1G      0.518     0.3114     0.8837        368        640: 100%|██████████| 5/5 [00:56<00:00, 11.37s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.91s/it]

                   all         15        240        0.9      0.942      0.943       0.78



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     89/100        11G     0.5094     0.3071     0.8875        278        640: 100%|██████████| 5/5 [00:54<00:00, 10.89s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.13s/it]

                   all         15        240      0.898      0.936      0.944      0.784



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     90/100      11.2G     0.5143     0.3114     0.8821        282        640: 100%|██████████| 5/5 [00:52<00:00, 10.41s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.06it/s]

                   all         15        240      0.899      0.935      0.948      0.792


Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, num_output_channels=3, method='weighted_average'), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     91/100      11.1G     0.4882     0.3035     0.8757        171        640: 100%|██████████| 5/5 [00:53<00:00, 10.80s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.46s/it]

                   all         15        240        0.9      0.931       0.95      0.791



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     92/100      11.1G     0.5063     0.3036     0.8855        116        640: 100%|██████████| 5/5 [00:45<00:00,  9.20s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.82s/it]

                   all         15        240        0.9      0.932      0.952      0.801



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     93/100      11.4G     0.4887     0.2989     0.8761        171        640: 100%|██████████| 5/5 [00:47<00:00,  9.48s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]

                   all         15        240      0.928      0.928      0.954      0.802



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     94/100      11.1G     0.4925     0.2982     0.8654        136        640: 100%|██████████| 5/5 [00:51<00:00, 10.34s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.89s/it]

                   all         15        240      0.912      0.955      0.953      0.802



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     95/100      11.1G     0.4832     0.2898      0.875        138        640: 100%|██████████| 5/5 [00:47<00:00,  9.41s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.45s/it]

                   all         15        240      0.914      0.958      0.958      0.804



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     96/100      11.1G     0.4668      0.283     0.8673        157        640: 100%|██████████| 5/5 [00:44<00:00,  8.87s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.85s/it]

                   all         15        240        0.9      0.954      0.956      0.805



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     97/100      11.1G     0.4823     0.2842     0.8656        158        640: 100%|██████████| 5/5 [00:46<00:00,  9.34s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.38s/it]

                   all         15        240        0.9      0.954      0.956      0.806



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     98/100      11.1G     0.4788     0.2834     0.8768        151        640: 100%|██████████| 5/5 [00:45<00:00,  9.05s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.43s/it]

                   all         15        240      0.911      0.956      0.957      0.806



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     99/100      11.1G     0.4753     0.2808     0.8671        170        640: 100%|██████████| 5/5 [00:42<00:00,  8.58s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.98s/it]

                   all         15        240       0.91      0.956      0.959      0.809



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    100/100      11.1G     0.4638     0.2736     0.8625        167        640: 100%|██████████| 5/5 [00:41<00:00,  8.26s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.82s/it]

                   all         15        240      0.906      0.936      0.956      0.803



100 epochs completed in 1.411 hours.
Optimizer stripped from runs\detect\train2\weights\last.pt, 51.2MB
Optimizer stripped from runs\detect\train2\weights\best.pt, 51.2MB

Validating runs\detect\train2\weights\best.pt...
Ultralytics 8.3.36  Python-3.12.4 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4060, 8187MiB)
YOLO11l summary (fused): 464 layers, 25,283,167 parameters, 0 gradients, 86.6 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.65it/s]


                   all         15        240       0.91      0.956      0.959      0.809
                   car         15         68      0.917      0.926      0.977      0.837
                   hen         15         15          1          1      0.995      0.844
              obstacle         15        131      0.948      0.977      0.989      0.829
                timber          7         16      0.941      0.994      0.988      0.788
                 water          7         10      0.746      0.882      0.846      0.748
Speed: 0.2ms preprocess, 32.1ms inference, 0.0ms loss, 1.9ms postprocess per image
Results saved to runs\detect\train2


## Load the model and test it

In [13]:
from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt

model = YOLO('best.pt')

result = model('test_3.jpg')

# plot the result
plot = result[0].plot()
plt.imshow(plot)
plt.show()

# save the result
result[0].save('test_3_result.jpg')


image 1/1 c:\VSCode\CrossyRoad\Crossy-Road-Course-Project\src\models\YOLOv11\test_3.jpg: 384x640 5 cars, 1 hen, 5 obstacles, 3 timbers, 1 water, 63.0ms
Speed: 1.1ms preprocess, 63.0ms inference, 0.5ms postprocess per image at shape (1, 3, 384, 640)


<Figure size 640x480 with 1 Axes>

'test_3_result.jpg'

## Create the grid

In [14]:
import numpy as np

def map_to_grid(image_size, grid_size, boxes, class_labels):
    
    width, height = image_size
    grid_width, grid_height = grid_size
    grid = np.zeros((grid_height, grid_width), dtype=int)

    cell_width = width / grid_width
    cell_height = height / grid_height

    for (x_min, y_min, x_max, y_max), label in zip(boxes, class_labels):
        # Determine the grid cell indices
        x_start = int(x_min // cell_width)
        y_start = int(y_min // cell_height)
        x_end = int(np.ceil(x_max / cell_width))
        y_end = int(np.ceil(y_max / cell_height))

        # Fill the grid with the object label
        for y in range(y_start, y_end):
            for x in range(x_start, x_end):
                grid[y, x] = label + 1

    return grid


In [20]:
import numpy as np

image_size = (425, 240)  # Image dimensions (width, height)
grid_size = (27, 24)    # Grid dimensions (N, M)

boxes = []
labels = []

for res in result:
    for box in res.boxes:
        x_min, y_min, x_max, y_max = box.xyxy[0].tolist()
        class_id = int(box.cls[0].item())
        boxes.append((x_min, y_min, x_max, y_max))
        labels.append(class_id)


grid = map_to_grid(image_size, grid_size, boxes, labels)
print(grid)


[[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 4]
 [4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 4]
 [1 1 1 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 4]
 [1 1 1 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 4]
 [1 1 1 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [1 1 1 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [1 1 1 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [1 1 1 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 2 2 2 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 2 2 2 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [3 3 3 0 0 0 1 1 1 1 1 1 1 0 0